name: Acordar Render

on:
  workflow_dispatch: # Permite execução manual
  schedule:
    - cron: '0 6 * * *'  # 08:00 em Moçambique (UTC+2 == 06:00 UTC)

jobs:
  wake-render:
    runs-on: ubuntu-latest
    name: Acordar app no Render via Puppeteer
    steps:
      - name: 🧾 Clonar repositório
        uses: actions/checkout@v3

      - name: 📦 Instalar Node.js e dependências
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🧪 Instalar Puppeteer
        run: npm install puppeteer

      - name: 🚀 Executar script Puppeteer
        run: node puppeteer-wake.js
